import type { APIContext } from 'astro';
import { publicUrl } from '../lib/urls';

export function GET({ site }: APIContext) {
  const guide = publicUrl(site, 'guides.md');
  return new Response(`# GPUI Omarchy\n\n> Native Rust components with Omarchy presentation, built on gpui-base.\n\n## Documentation\n\n- [Complete Guides and public API details](${guide}): The authoritative single-page Markdown guide. Read this before generating application code; it includes dependency versions, complete examples, state ownership and component constraints.\n- [Guides in HTML](${publicUrl(site, 'guides/')}): The same content with chapter navigation.\n\n## Framework reference\n\n- [GPUI Kit documentation](https://gpui-kit.com/llms-full.txt): Framework and layer reference. Use gpui_kit::base for Omarchy composition; the optional component layer has its own bootstrap.\n\n## Source and runnable examples\n\n- [Public exports](https://github.com/huacnlee/gpui-omarchy/blob/main/src/lib.rs): Check exact exported names.\n- [First application](https://github.com/huacnlee/gpui-omarchy/blob/main/examples/hello.rs): Complete desktop entry point.\n- [Component gallery](https://github.com/huacnlee/gpui-omarchy/blob/main/examples/gallery/app.rs): State initialization, callbacks and composition.\n\n## Usage boundaries\n\nDepend on gpui-kit 0.6.0 with default-features = false and gpui-omarchy. Import framework types from gpui_kit and base state from gpui_kit::base; use gpui_kit::application() for the desktop entry point. Initialize once, retain entities in the view, and update controlled values in callbacks. Do not invent methods: confirm them in the guide or the pinned dependency documentation. The WebAssembly gallery is a rendered demo, not a machine-readable API reference.\n`, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
