// The host installs gpui-omarchy-shell's native catalog into this runtime slot.
export {
  Button,
  ChoiceItem,
  ButtonGroup,
  TabList,
  Input,
  Textarea,
  NumberInput,
  Calendar,
  Slider,
  OtpInput,
  Tab,
  Tabs,
  ToggleGroup,
  FocusScope,
  Tooltip,
  Checkbox,
  Switch,
  Radio,
  Toggle,
  Panel,
  Separator,
  VerticalSeparator,
  Keycap,
  Badge,
  EmptyState,
  Progress,
  Toast,
  Table,
  TableRow,
  TableHead,
  TableCell,
  DialogBackdrop,
  DialogPopup,
  DialogTitle,
  DialogDescription,
  SheetSurface,
  PopoverSurface,
  AccordionPanel,
  Avatar,
  AvatarImage,
  Icon,
  Markdown,
  Html,
} from "gpui-component";

// Retain the shell's editing state API, including value, focus and events.
export { InputState, TextareaState, CalendarState, SliderState, OtpState } from "gpui-base";
